import profileimg from "./images/profileimg.jpg";

export const ocArray = [
  {
    image: profileimg,
    name: "Gauri",
    linkedinId: "https://www.linkedin.com/in/id/",
    emailId: "mailto:emailid@gmail.com",
    post: "Overall Co-ordinator",
  },
  {
    image: profileimg,
    name: "Pratyusha",
    linkedinId: "https://www.linkedin.com/in/id/",
    emailId: "mailto:emailid@gmail.com",
    post: "Overall Co-ordinator",
  },
];
export const cArray = [
  {
    img: profileimg,
    name: "Amrit",
    post: "Web Development",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Tanuja Kaleli",
    post: "Research and Projects",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Advaith Kannan",
    post: "Marketing and Fundraising",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Deepak",
    post: "Social Media",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Abhishek Kumar",
    post: "Events",
    linkedinId: "#",
    emailId: "#",
  },
];
export const secyArray = [
  {
    img: profileimg,
    name: "Manasvi Nidugala",
    post: "Marketing",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Eeshwari Sunkersett",
    post: "Marketting ",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Suryansh Dwivedi",
    post: "Marketing",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Asif nawaz ",
    post: "Marketing",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Sneh",
    post: "Marketing",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Vanshika Yadav",
    post: "Marketing",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Pradeep Kumar",
    post: "Web Dev",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Karan Jangid",
    post: "Web Dev",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Bhavya Garg",
    post: "Web Dev",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Lakshit Sharma",
    post: "Research",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Debarpita Dash",
    post: "Research",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Adhiraj Gupta",
    post: "Research ",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Aryan Mittal ",
    post: "Research ",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Yeleena Vimal",
    post: "Research ",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Jonnala Hema Phani Sri",
    post: "Social Media",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Deepak Gautam",
    post: "Social Media",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Aradhya Gautam",
    post: "Social Media",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Krrish khandelwal",
    post: "Social Media",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "ADRISH CHAKRABARTI",
    post: "Events",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Nischay Patel",
    post: "Events",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Anuj Gargya",
    post: "Events",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Aarsh Choudhari ",
    post: "Events",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Rajavardhan Ramavath",
    post: "Events",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Keshav Khandelwal",
    post: "Events",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Kritnandan",
    post: "Events",
    linkedinId: "#",
    emailId: "#",
  },
  {
    img: profileimg,
    name: "Hariom Singh",
    post: "Events",
    linkedinId: "#",
    emailId: "#",
  },
];
